services:
  api:
    build: 
      context: ./
      dockerfile: Dockerfile
    tty: true
    ports:
      - 8000:8000
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./src:/usr/share/api-classroom/src
  database:
    image: mysql
    tty: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3306"]
      interval: 15s
      timeout: 10s
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=classroom
